on:
  push:
    branches:
      - master
  schedule:
    - cron:  '10 8,9,10,12,13,17 * * 1-5'

jobs:
  en_AU:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-australia.com/api/mission_type_data.json > mtd/en_AU.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"

    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_AU
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  cs_CZ:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: en_AU
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operacni-stredisko.cz/api/mission_type_data.json > mtd/cs_CZ.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"

    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update cs_CZ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  de_DE:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: cs_CZ
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.leitstellenspiel.de/api/mission_type_data.json > mtd/de_DE.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update de_DE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  da_DK:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: de_DE
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.alarmcentral-spil.dk/api/mission_type_data.json > mtd/da_DK.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update da_DK
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  es_ES:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: da_DK
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.centro-de-mando.es/api/mission_type_data.json > mtd/es_ES.json
        
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update es_ES
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  fi_FI:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: es_ES
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.hatakeskuspeli.com/api/mission_type_data.json > mtd/fi_FI.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update fi_FI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  fr_FR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: fi_FI
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operateur112.fr/api/mission_type_data.json > mtd/fr_FR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update fr_FR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  it_IT:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: fr_FR
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operatore112.it/api/mission_type_data.json > mtd/it_IT.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update it_IT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  ja_JP:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: it_IT
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-japan.com/api/mission_type_data.json > mtd/ja_JP.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ja_JP
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  ko_KR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ja_JP
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-korea.com/api/mission_type_data.json > mtd/ko_KR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ko_KR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  nl_NL:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ko_KR
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.meldkamerspel.com/api/mission_type_data.json > mtd/nl_NL.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update nl_NL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  nb_NO:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: nl_NL
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.nodsentralspillet.com/api/mission_type_data.json > mtd/nb_NO.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update nb_NO
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  pl_PL:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: nb_NO
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operatorratunkowy.pl/api/mission_type_data.json > mtd/pl_PL.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update pl_PL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  pt_PT:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: pl_PL
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.jogo-operador112.com/api/mission_type_data.json > mtd/pt_PT.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update pt_PT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  sv_SE:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: pt_PT
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
       git pull
       curl -X GET https://www.larmcentralen-spelet.se/api/mission_type_data.json > mtd/sv_SE.json
               
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update sv_SE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  en_GB:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: sv_SE
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief.co.uk/api/mission_type_data.json > mtd/en_GB.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_GB
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  

  en_US:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: en_GB
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief.com/api/mission_type_data.json > mtd/en_US.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v2.0.2
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.6 
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_US
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  
